### PR TITLE
feat: parse Github requests #6

### PR DESCRIPTION
**Pull request by jvonhacht**
**Contains**

- A utils folder that contains JsonUtil. This file contains two methods, one for converting a string into a JSONObject and one for extracting the relevant data from a Github post request.
- A GithubController that has a method `handlePost` which is called when `<name>.johvh.se/api/github` is requested with a post.
- Two tests which check that the JsonUtil class handles as expected

**Wait merge until #20  is merged**

### CODE REVIEW

**Review by jonasjungaker — CHANGES_REQUESTED** [review]
Can we put these methods in another class in order to keep the handler clean and lean?

**Comment by jvonhacht** [comment]
> Can we put these methods in another class in order to keep the handler clean and lean?

That is a good idea. I just created a new PR where Spark (another web server framework) is used instead of Jetty. Read the PR and issue for the reasons why. 

When I refactor this feature to Spark I'll consider placing them in a separate file

**Review by jonasjungaker — DISMISSED** [review]

**Review by jonasjungaker — DISMISSED** [review]

**Comment by jonasjungaker** [comment]
Is this mergable?

**Comment by jvonhacht** [comment]
> Is this mergable?

Yes but merge #20 first

**Comment by jvonhacht** [comment]
Should probably be squashed at this point since some `feat:` commits don't have tests, see #10. This pr also changes the Github post URL to `<name>.johvh.se/api/github` which breaks the current webhooks.

**Review by jonasjungaker — APPROVED** [review]

**Pull request merged**
